# Generated by Django 3.2.22 on 2023-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='biblioteca_App.Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('N', 'Novela'), ('C', 'Cuento'), ('P', 'Poesía'), ('T', 'Teatro'), ('O', 'Otros')], max_length=1),
        ),
    ]
